pipeline {
    agent any

    stages {

        stage('clean') {
            steps {
                sh 'mvn clean'
                    }
                }

        stage('compile') {
            steps {
                sh 'mvn compile'
                    }
                }
         stage('test') {
            steps {
                sh 'mvn test'
            }
         }
        stage('build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }

    post {
        success {
            sh 'scp target/*.war mgk@192.168.18.129:/home/mgk/linux/tomcat/webapps/'
        }
        failure {
            echo "build failed"
        }
    }
}
